### ISSUE TITLE
Different Store Views - same identifier

### ISSUE THREAD

**Issue by uncenteredDiv** [scandiwebcom/MagentoMenuManager#2]
I'm creating a multi language shop with different menu blocks in the footer.
The links in the menus are different for each language - but the menu blocks content don't change when i change the language.

Is there a way to get the menu blocks via identifier and not via ID?
Or do i have to add the menu block twice in the layout - so that only one block gets rendered each time for the specific language?

You might got a better idea?

**Comment by scandiwebcom** [comment]
Hi, @Skinwalker !

You can easily create multiple menus with the same identifier and just assign them to the appropriate store. In that case - you will need to add menu block only once with the mentioned identifier. 

Re: “is there a way to get the menu blocks via identifier and not via ID?” Menus are already added using identifier instead of hardcoded ID.

Hope this brings some clarity.

**Comment by uncenteredDiv** [comment]
Ok - now i got it ... sorry for the stupid question.
Changed the ID to the identifier and know its working like a charm.

**Comment by scandiwebcom** [comment]
No worries! Glad we could help. 👍
